version: "3.8"

networks:
  traefik:
    external:
      name: devtools_default

services:
  nginx:
    build: infra/nginx
    links:
      - php
    volumes:
      - "./:/var/www/html"
    labels:
      - "traefik.http.routers.allcoin.rule=Host(`allcoin.local`)"
    networks:
      - traefik
  php:
    build: infra/php
    volumes:
      - "./:/var/www/html"
    networks:
      - traefik
